INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('105','Two strangers awaken in a room with no recollection of how they got there, and soon discover theyre pawns in a deadly game perpetrated by a notorious serial killer.','https://m.media-amazon.com/images/M/MV5BMzQ2ZTBhNmEtZDBmYi00ODU0LTgzZmQtNmMxM2M4NzM1ZjE4XkEyXkFqcGdeQXVyNjE5MjUyOTM@._V1_.jpg', 3,'James Wan', '103', '7.6','SAW', '2004');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('106','A detective and his team must rescue 8 people trapped in a factory by the twisted serial killer known as Jigsaw.','https://m.media-amazon.com/images/M/MV5BMTI4OTQ2MTQzM15BMl5BanBnXkFtZTcwNzE5OTQ1MQ@@._V1_.jpg', 3,'Darren Lynn Bousman', '93', '6.6','SAW III', '2005');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('107','A father and daughter are on their way to dance camp when they spot the girls best friend on the side of the road. When they stop to offer the friend a ride, their good intentions soon result in terrible consequences.','https://m.media-amazon.com/images/M/MV5BY2I5NzM3Y2QtNGY4NS00Njg5LWI2OGYtZDhlN2UzOWJjMDUxXkEyXkFqcGdeQXVyODE0OTU5Nzg@._V1_SY1000_SX675_AL_.jpg', 3,'Veena Sud', '97', '5.7','THE LIE', '2018');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('108','Terror grips a small mountain town as bodies are discovered after each full moon. Losing sleep, raising a teenage daughter, and caring for his ailing father, officer Marshall struggles to remind himself theres no such thing as werewolves.','https://m.media-amazon.com/images/M/MV5BOWZlMDBiMmItMWU0Ny00MGIzLWI1NTQtZDEwMjM0MzBiYjhkXkEyXkFqcGdeQXVyMzIxMjMyODY@._V1_UX182_CR0,0,182,268_AL_.jpg', 3,'Jim Cummings', '83', '6.2','THE WOLF OF SNOW HOLLOW', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('109','When Cecilias abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.','https://m.media-amazon.com/images/M/MV5BZjFhM2I4ZDYtZWMwNC00NTYzLWE3MDgtNjgxYmM3ZWMxYmVmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 3,'Leigh Whannell', '124', '7.1','THE INVISIBLE MAN', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('110','A young boy stumbles onto a witch convention and must stop them, even after he has been turned into a mouse.','https://m.media-amazon.com/images/M/MV5BMjI1MDg5NzAyMV5BMl5BanBnXkFtZTgwNzU5Mzk4NjE@._V1_UX182_CR0,0,182,268_AL_.jpg', 3,'Nicolas Roeg', '91', '6.8','THE WITCHES ', '1990');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('111','An incredibly gifted pianist makes a Faustian bargain to overtake her older sister at a prestigious institution for classical musicians.','https://m.media-amazon.com/images/M/MV5BNjU3NGRlOGUtMGYzMS00YzJkLWE2NzMtMTM0YmZmNjBiZTZkXkEyXkFqcGdeQXVyODE0OTU5Nzg@._V1_UX182_CR0,0,182,268_AL_.jpg', 3,' Zu Quirke', '90', '5.6','NOCTURNE', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('112','After losing his wife and his memory in a car accident, a single father undergoes an agonizing experimental treatment that causes him to question who he really is.','https://m.media-amazon.com/images/M/MV5BZDExM2Y5MzYtYmMxNS00ZWU4LTkwYzEtY2JiMWU2NTFlZWM5XkEyXkFqcGdeQXVyODE0OTU5Nzg@._V1_UX182_CR0,0,182,268_AL_.jpg', 3,' Emmanuel Osei-Kuffour', '100', '6','BLACK BOX', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('113','Years following the events of The Shining (1980), a now-adult Dan Torrance must protect a young girl with similar powers from a cult known as The True Knot, who prey on children with powers to remain immortal.','https://m.media-amazon.com/images/M/MV5BYmY3NGJlYTItYmQ4OS00ZTEwLWIzODItMjMzNWU2MDE0NjZhXkEyXkFqcGdeQXVyMzQzMDA3MTI@._V1_UX182_CR0,0,182,268_AL_.jpg', 3,'Mike Flanagan', '152', '7.3','DOCTOR SLEEP', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('114','Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again.','https://m.media-amazon.com/images/M/MV5BNzk1OGU2NmMtNTdhZC00NjdlLWE5YTMtZTQ0MGExZTQzOGQyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', 3,'John Carpenter', '91', '7.8','HALLOWEEN', '1978');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('115','A retired CIA agent travels across Europe and relies on his old skills to save his estranged daughter, who has been kidnapped while on a trip to Paris.','https://m.media-amazon.com/images/M/MV5BMTM4NzQ0OTYyOF5BMl5BanBnXkFtZTcwMDkyNjQyMg@@._V1_.jpg', 1,'Pierre Morel', '90', '7.8','TAKEN', '2008');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('116','In Istanbul, retired CIA operative Bryan Mills and his wife are taken hostage by the father of a kidnapper Mills killed while rescuing his daughter.','https://m.media-amazon.com/images/M/MV5BMTkwNTQ0ODExOV5BMl5BanBnXkFtZTcwNjU3NDQwOA@@._V1_SY1000_CR0,0,674,1000_AL_.jpg', 1,'Olivier Megaton', '92', '6.3','TAKEN 2', '2012');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('117','Accused of a ruthless murder he never committed or witnessed, Bryan Mills goes on the run and brings out his particular set of skills to find the true killer and clear his name.','https://m.media-amazon.com/images/M/MV5BNjM5MDU3NTY0M15BMl5BanBnXkFtZTgwOTk2ODU2MzE@._V1_SY1000_CR0,0,674,1000_AL_.jpg', 1,'Olivier MÃ©gaton', '108', '6','TAKEN 3', '2014');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('118','When Enola Holmes-Sherlocks teen sister-discovers her mother missing, she sets off to find her, becoming a super-sleuth in her own right as she outwits her famous brother and unravels a dangerous conspiracy around a mysterious young Lord.','https://m.media-amazon.com/images/M/MV5BZjNkNzk0ZjEtM2M1ZC00MmMxLTlmOWEtNWRlZTc1ZTUyNzY4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX182_CR0,0,182,268_AL_.jpg', 1,' Harry Bradbeer', '123', '6.6','ENOLA HOLMES', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('119','In a monster-infested world, Joel (Dylan OBrien) learns his girlfriend is just 80 miles away. To make the dangerous journey, Joel discovers his inner hero to be with the girl of his dreams.','https://m.media-amazon.com/images/M/MV5BYWVkMWEyMDUtZTVmOC00MTYxLWE1ZTUtNjk4M2IzMjY2OTIxXkEyXkFqcGdeQXVyMDk5Mzc5MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 1,'Michael Matthews', '109', '7.1','LOVE AND MONSTERS', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('120','A young Chinese maiden disguises herself as a male warrior in order to save her father.','https://m.media-amazon.com/images/M/MV5BNDliY2E1MjUtNzZkOS00MzJlLTgyOGEtZDg4MTI1NzZkMTBhXkEyXkFqcGdeQXVyNjMwMzc3MjE@._V1_UX182_CR0,0,182,268_AL_.jpg', 1,' Niki Caro', '115', '5.4','MULAN', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('121','An augmented human and Sarah Connor must stop an advanced liquid Terminator from hunting down a young girl, whose fate is critical to the human race.','https://m.media-amazon.com/images/M/MV5BOWExYzVlZDgtY2E1ZS00NTFjLWFmZWItZjI2NWY5ZWJiNTE4XkEyXkFqcGdeQXVyMTA3MTA4Mzgw._V1_UX182_CR0,0,182,268_AL_.jpg', 1,'Tim Miller', '128', '6.2','TERMINATOR: DARK FATE', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('122','An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.','https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX182_CR0,0,182,268_AL_.jpg', 1,'Chris Columbus', '152', '7.6','HARRY POTTER AND THE SORCERER;S STONE', '2001');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('123','After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos actions and restore balance to the universe.','https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX182_CR0,0,182,268_AL_.jpg', 1,' Joe Russo', '181', '8.4','AVENGERS:endgame', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('124','A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.','https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg', 1,'Christopher Nolan', '169', '8.6','INTERESTELLAR', '2014');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('125','Despite his devotion to his hometown of Salem (and its Halloween celebration), Hubie Dubois is a figure of mockery for kids and adults alike. But this year, something is going bump in the night, and its up to Hubie to save Halloween.','https://m.media-amazon.com/images/M/MV5BMTE0N2EyMzgtMWJhZS00ZWNmLThjZmQtMjcxYTk1NTJiMGVkXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UY268_CR16,0,182,268_AL_.jpg', 2,'Steve Brill', '102', '5.2','HUBIE HALLOWEEN', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('126','A curious youngster moves to Salem, where he struggles to fit in before awakening a trio of diabolical witches that were executed in the 17th century.','https://m.media-amazon.com/images/M/MV5BMWUxNWI0YTYtY2RiZS00ZjNmLTg4ZGUtNDI0Mzk4NmQ5NWE5XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,'Kenny Ortega', '96', '6.9','HOCUS POCUS', '1993');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('127','A tribe of cats called the Jellicles must decide yearly which one will ascend to the Heaviside Layer and come back to a new Jellicle life.','https://m.media-amazon.com/images/M/MV5BNjRlNTY3MTAtOTViMS00ZjE5LTkwZGItMGYwNGQwMjg2NTEwXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,'Tom Hooper', '110', '2.8','CATS', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('128','Con artists plan to fleece an eccentric family using an accomplice who claims to be their long-lost uncle.','https://m.media-amazon.com/images/M/MV5BODc1NmY0MDUtNjUzNS00ODdhLWJlN2ItMTgwZjczZjI0MDkyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UY268_CR11,0,182,268_AL_.jpg', 2,'Barry Sonnenfeld', '99', '6.9','THE ADDAMS FAMILY', '1991');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('129','A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who cross her path.','https://m.media-amazon.com/images/M/MV5BOTgzMzE4MGItZDgxYS00ZGEwLWE3YTctZWY3ZDAyMTk0ZGU4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,'Emerald Fennell', '113', '6.2','PROMISSING YOUNG WOMAN', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('130','An American expat tries to sell off his highly profitable marijuana empire in London, triggering plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.','https://m.media-amazon.com/images/M/MV5BMTlkMmVmYjktYTc2NC00ZGZjLWEyOWUtMjc2MDMwMjQwOTA5XkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,'Guy Ritchie', '113', '7.9','THE GENTLEMAN', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('131','A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywoods Golden Age in 1969 Los Angeles.','https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,' Quentin Tarantino', '161', '7.6','ONCE UPON A TIME...IN HOLLYWOOD', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('132','Upset that he has to share the room he loves with his grandfather, Peter decides to declare war in an attempt to get it back.','https://m.media-amazon.com/images/M/MV5BNTlkZDQ1ODEtY2ZiMS00OGNhLWJlZDctYzY0NTFmNmQ2NDAzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,' Tim Hill', '94', '5.5','THE WAR WITH GRANDPA', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('133','A detective investigates the death of a patriarch of an eccentric, combative family.','https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,' Rian Johnson', '130', '7.9','KNIVES OUT', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('134','The spirits of a deceased couple are harassed by an unbearable family that has moved into their home, and hire a malicious spirit to drive them out.','https://m.media-amazon.com/images/M/MV5BZDdmNjBlYTctNWU0MC00ODQxLWEzNDQtZGY1NmRhYjNmNDczXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', 2,'Tim Burton', '92', '7.5','BEETLEJUICE', '1988');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('135','The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention in Chicago, Illinois.','https://m.media-amazon.com/images/M/MV5BYjYzOGE1MjUtODgyMy00ZDAxLTljYTgtNzk0Njg2YWQwMTZhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,' Aaron Sorkin', '129', '8','THE TRIAL OF THE CHICAGO 7', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('136','Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality.','https://m.media-amazon.com/images/M/MV5BZmE1NmVmN2EtMjZmZC00YzAyLWE4MWEtYjY5YmExMjUxODU1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,'Antonio Campos', '138', '7.1','THE DEVIL ALL THE TIME', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('137','A patriarch of a wealthy and powerful family suddenly passes away, leaving his daughter with a shocking secret inheritance that threatens to unravel and destroy the family.','https://m.media-amazon.com/images/M/MV5BYTYzZjE4NmEtZjQ2NC00NjNjLTlhNTItNjM3YTA3YTQyODk1XkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,'Vaughn Stein', '111', '5.5','INHERITANCE', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('138','In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.','https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,'Todd Phillips', '122', '8.5','JOKER', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('139','Ava is a deadly assassin who works for a black ops organization, traveling the globe specializing in high profile hits. When a job goes dangerously wrong she is forced to fight for her own survival.','https://m.media-amazon.com/images/M/MV5BMTMzMTg1MjgtOWNhYy00NmZmLWExOTctMjA2OTZhZDFkNDhhXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,'Tate Taylor', '96', '5.3','AVA', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('140','Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.','https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,' Bong Joon Ho', '132', '8.6','PARASITE', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('141','A young newlywed arrives at her husbands imposing family estate on a windswept English coast and finds herself battling the shadow of his first wife, Rebecca, whose legacy lives on in the house long after her death.','https://m.media-amazon.com/images/M/MV5BYzgzNGFkNDItZTJkZC00NzJkLTk2OWMtNzliM2I5YzQxYjkxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,'Ben Wheatley', '121', '6.6','REBECCA', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('142','2038: George Almore is working on a true human-equivalent AI. His latest prototype is almost ready. This sensitive phase is also the riskiest. Especially as he has a goal that must be hidden at all costs: being reunited with his dead wife.','https://m.media-amazon.com/images/M/MV5BMzFkNTRiMzYtODM2MS00YWQ2LThkNTUtMDE1Y2E2YjAwYTUxXkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,' Gavin Rothery', '109', '6.3','ARCHIVE', '2020');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('143','A couple travels to Sweden to visit a rural hometowns fabled mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.','https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,'Ari Aster', '148', '7.1','MIDSOMMAR:the directors cut', '2019');
INSERT INTO `moviesdb`.`movie`
(`id`,`description`, `imageurl`,`category_ref`,`director`,`duration`,`rating`,`title`,`year`) VALUES ('144','A superstitious mother is convinced that her daughters new boyfriend is the reincarnation of a man who tried to kill her 30 years ago.','https://m.media-amazon.com/images/M/MV5BZjc1YWE4YTUtM2UzOS00MDUwLTkxNmYtZGFkZGViZDY0MWRlXkEyXkFqcGdeQXVyODE0OTU5Nzg@._V1_UX182_CR0,0,182,268_AL_.jpg', 4,'Rajeev Dassani', '90', '4.5','evil eye', '2020');
