/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Movie } from './movie';
import { MovieClick } from './movieClick';
import { PreferencesForm } from './preferencesForm';
import { Role } from './role';


export interface User { 
    active?: boolean;
    encryptedPassword?: string;
    formCompleted?: number;
    fullName?: string;
    id?: number;
    movieclicks?: Array<MovieClick>;
    moviesSeen?: Array<Movie>;
    preferencesForm?: PreferencesForm;
    roles?: Array<Role>;
    username?: string;
}
